from typing import TypedDict, List, Dict, Any, Optional

# Importarás tus schemas Pydantic aquí
from .schemas.masterChecklist import MasterChecklist

class TenderAnalysisState(TypedDict):
    """
    Represents the full state of the tender analysis pipeline.
    """
    # --- Input Data ---
    # The raw text from the tender document
    tenderText: str
    # The list of proposal objects received from the API
    proposals: List[Dict[str, Any]]

    # --- Derived Data (generated by the agent) ---
    # The structured checklist of requirements extracted from the tenderText
    masterChecklist: Optional[MasterChecklist]
    # The list of detailed analysis results for each proposal
    analysisResults: Optional[List[Dict[str, Any]]]
    
    # --- Final Output ---
    # The final, clean JSON object for the frontend
    finalReport: Optional[Dict[str, Any]]
